---
- name: Provision the Ubuntu 20.04 docker native platform host
  hosts: localhost
  connection: local
  vars:
    environments_dir: "{{ playbook_dir }}/.."
    ros_workspace_dir: "{{ ansible_facts['env']['HOME'] }}/Jugglebot/ros_ws"

  tasks:

  - name: Provision the Bash default files
    copy:
      remote_src: yes
      src: /etc/skel/
      dest: "{{ ansible_facts['env']['HOME'] }}"
      force: no

  - name: Require that the jugglebot Conda environment is activated
    assert:
      that: ansible_facts['env']['CONDA_DEFAULT_ENV'] == 'jugglebot'
      fail_msg: '[ERROR]: This playbook expects for the jugglebot conda environment to be activated. Activate that environment using the following command: `conda activate jugglebot`'
      quiet: yes

  - name: Provision the Ubuntu environment
    import_tasks: "{{ environments_dir }}/ubuntu-common/dev_env_tasks.yml"
    vars:
      environments_dir: "{{ playbook_dir }}/.."

  - name: Install the Docker CLI package
    package:
      name: docker-ce-cli
      state: present
    become: yes

  - name: Install the Jugglebot ROS dependencies
    command:
      cmd: "/usr/bin/rosdep install -i --from-path src --rosdistro {{ ros_version_codename }}"
      chdir: "{{ ros_workspace_dir }}"
 
