---
- name: Provision the Ubuntu 20.04 docker native platform host
  hosts: localhost
  connection: local
  vars:
    environments_dir: "{{ playbook_dir }}/.."
    home_dir: "{{ ansible_facts['env']['HOME'] }}"
    ros_workspace_dir: "{{ home_dir }}/Jugglebot/ros_ws"
    jugglebot_rc_rendered_filepath: "{{ home_dir }}/.jugglebot/host_setup/defaults/jugglebot_rc.yml"

  tasks:

  - name: Provision the Bash default files
    copy:
      remote_src: yes
      src: /etc/skel/
      dest: "{{ home_dir }}"
      force: no

  - name: Require that the jugglebot Conda environment is activated
    assert:
      that: ansible_facts['env']['CONDA_DEFAULT_ENV'] == 'jugglebot'
      fail_msg: '[ERROR]: This playbook expects for the jugglebot conda environment to be activated. Activate that environment using the following command: `conda activate jugglebot`'
      quiet: yes

  - name: Provision the Ubuntu environment
    import_tasks: "{{ environments_dir }}/ubuntu-common/dev_env_tasks.yml"
    vars:
      environments_dir: "{{ playbook_dir }}/.."

  - name: Install the Docker CLI package
    package:
      name: docker-ce-cli
      state: present
    become: yes

  - name: Update the rosdep package manager
    command:
      cmd: /usr/bin/rosdep update

  - name: Read the ROS codename
    command:
      cmd: "/usr/bin/yq -r .ros.version_codename '{{ jugglebot_rc_rendered_filepath }}'"
    register: yq_command_result
    changed_when: False

  - name: Set the ROS codename variable
    set_fact:
      ros_version_codename: "{{ yq_command_result.stdout }}"

  - name: Install the Jugglebot ROS dependencies
    shell:
      cmd: "source /opt/ros/{{ ros_version_codename }}/setup.bash && rosdep install -i --from-path src --rosdistro {{ ros_version_codename }}"
      executable: /usr/bin/bash
      chdir: "{{ ros_workspace_dir }}"
 
