---
- name: Provision the Ubuntu host in the Docker container
  hosts: localhost
  connection: local
  vars:
    environments_dir: "{{ playbook_dir }}/.."
    ros_workspace_dir: "{{ playbook_dir }}/../../ros_ws"
    home_dir: "{{ ansible_facts['env']['HOME'] }}"
    ubuntu_codename: "{{ ansible_facts['distribution_release'] }}"
    upgrade_packages_enabled: "{{ upgrade_packages_enabled__ | bool }}"
    jugglebot_config_dir: "{{ home_dir }}/.jugglebot"

  tasks:

  - name: Provision the Bash default files
    copy:
      remote_src: yes
      src: /etc/skel/
      dest: "{{ home_dir }}"
      force: no

  - name: Read the config defaults file
    slurp:
      src: "{{ environments_dir }}/ubuntu-common/config_defaults.yml"
    register: config_defaults_read_result

  - name: Set the default_config variable
    set_fact:
      default_config: >
        {{ config_defaults_read_result.content | b64decode | from_yaml }}

  - name: Read the copied config file
    slurp:
      src: "{{ jugglebot_config_dir }}/config.yml"
    register: copied_config_read_result

  - name: Set the copied_config variable
    set_fact:
      copied_config: >
        {{ copied_config_read_result.content | b64decode | from_yaml }}

  - name: Import the package version lookup dicts
    include_vars: "{{ environments_dir }}/ubuntu-common/package_version_lookup_vars.yml"

  - name: Create the overlayed config
    set_fact:
      config: >
        {{ default_config
        | combine(copied_config, recursive=True) }}

  - name: Require that the host-provisioning Conda environment is activated
    assert:
      that: ansible_facts['env']['CONDA_DEFAULT_ENV'] == 'host-provisioning'
      fail_msg: >
        [ERROR]: This playbook expects for the host-provisioning Conda
        environment to be activated. Typically, that should have been done by
        sourcing `ubuntu-common/base_setup.sh` prior to running this playbook.
      quiet: yes

  - name: Provision the Ubuntu environment
    import_tasks: "{{ environments_dir }}/ubuntu-common/dev_env_tasks.yml"
    vars:
      environments_dir: "{{ playbook_dir }}/.."

  - name: Update the rosdep package manager
    command:
      cmd: /usr/bin/rosdep update

  - name: Install the Jugglebot ROS dependencies
    shell:
      cmd: >
        source /opt/ros/{{ ros_version_codename }}/setup.bash
        && rosdep install -i --from-path src --rosdistro {{ ros_version_codename }}
      executable: /usr/bin/bash
      chdir: "{{ ros_workspace_dir }}"

