---
- name: Provision the Ubuntu host in the Docker container
  hosts: localhost
  connection: local
  vars:
    environments_dir: "{{ playbook_dir }}/.."
    ros_workspace_dir: "{{ playbook_dir }}/../../ros_ws"
    home_dir: "{{ ansible_facts['env']['HOME'] }}"
    ubuntu_codename: "{{ ansible_facts['distribution_release'] }}"
    upgrade_packages_enabled: "{{ upgrade_packages_enabled__ | bool }}"

  tasks:

  - name: Provision the Bash default files
    copy:
      remote_src: yes
      src: /etc/skel/
      dest: "{{ home_dir }}"
      force: no

  - name: Require that the host-provisioning Conda environment is activated
    assert:
      that: ansible_facts['env']['CONDA_DEFAULT_ENV'] == 'host-provisioning'
      fail_msg: >
        [ERROR]: This playbook expects for the host-provisioning Conda
        environment to be activated. Activate that environment using the
        following command: `conda activate host-provisioning`
      quiet: yes

  - name: Provision the Ubuntu environment
    import_tasks: "{{ environments_dir }}/ubuntu-common/dev_env_tasks.yml"
    vars:
      environments_dir: "{{ playbook_dir }}/.."

  - name: Update the rosdep package manager
    command:
      cmd: /usr/bin/rosdep update

  - name: Import the package version lookup dicts
    include_vars: "{{ environments_dir }}/ubuntu-common/package_version_lookup_vars.yml"

  - name: Set the ros_version_codename variable
    set_fact:
      ros_version_codename: "{{ ubuntu_codename_to_ros_codename[ubuntu_codename] }}"

  - name: Install the Jugglebot ROS dependencies
    shell:
      cmd: >
        source /opt/ros/{{ ros_version_codename }}/setup.bash
        && rosdep install -i --from-path src --rosdistro {{ ros_version_codename }}
      executable: /usr/bin/bash
      chdir: "{{ ros_workspace_dir }}"
 
